### ISSUE TITLE
建议在会议筛选栏增加“USS-A”的筛选项

### ISSUE THREAD

**Issue by Jinzizhisir** [ZJUshine/usslab-conference-ddls#1]
目前在会议级别处，仅能筛选CCF-A,CCF-B等。
但是众所周知，USSLAB的baseline是高于CCF的，比如著名CCF-A会议AAA在USSLAB仅为B级会议。
所以希望能够增加USS-A,USS-B等选项，让网站更适用于USSLAB成员。

最后感谢ZJUSHINE，已watch/star/fork一键三连

**Comment by Jinzizhisir** [comment]
抱歉，有个typo，AAA应为AAAI

**Comment by ZJUshine** [comment]
感谢 我会尽快修改

**Comment by ZJUshine** [comment]
⭐️已经修复！⭐️
